name: CI for macOS with Autotools

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout stable branch
      uses: actions/checkout@v2
      with:
        ref: stable

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
        eval "$(/opt/homebrew/bin/brew shellenv)"

    - name: Install Autotools
      run: |
        brew install autoconf automake

    - name: Run aclocal
      run: aclocal -I .

    - name: Run automake
      run: automake --add-missing --copy

    - name: Run autoconf
      run: autoconf      

    - name: Configure
      run: ./configure  CXXFLAGS="-std=c++17"

    - name: Build
      run: make

    - name: Run tests
      run: make check

    - name: git diff
      run: git diff

    - name: Archive binary
      run: zip -j pasmo-macos.zip pasmo

    - name: Archive all
      run: zip -R pasmo-macos-all.zip *

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pasmo-macos
        path: pasmo-macos.zip

    - name: Upload all
      uses: actions/upload-artifact@v3
      with:
        name: pasmo-macos-all
        path: pasmo-macos-all.zip
